steps:
  - task: NodeTool@0
    displayName: 'Use Node 16.x'
    inputs:
      versionSpec: 16.x
    
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: $(npm_config_cache)
    displayName: Cache npm

  - script: |
      npm ci
    displayName: 'Install project dependencies'
  - script: |
      npm run create:suite SHEET=Regression
    displayName: 'Run the tests preparation'
  - script: |
      npm run test
    displayName: 'Run the tests'
    env:
      PASSWORD: $(password)
  
  - task: PublishTestResults@2
    displayName: 'Publish the test reports'
    inputs:
      testResultsFiles: './test-results/results/results.xml'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish screenshots'
    inputs:
      pathtoPublish: screenshots
      artifactName: screenshots
    continueOnError: true